# Generated by Django 5.2 on 2025-05-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devtools', 'Dev Tools')], max_length=20)),
                ('icon', models.CharField(choices=[('fa-brands fa-python', 'Python'), ('fa-brands fa-html5', 'HTML'), ('fa-brands fa-css3-alt', 'CSS'), ('fa-brands fa-js', 'JavaScript'), ('fa-solid fa-wind', 'Tailwind CSS'), ('fa-solid fa-leaf', 'Django'), ('fa-solid fa-database', 'MySQL'), ('fa-brands fa-react', 'React'), ('fa-solid fa-code', 'Other')], default='fa-solid fa-code', max_length=50)),
                ('proficiency', models.IntegerField(default=80, help_text='Percentage skill level')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devtools', 'Dev Tools')], max_length=20)),
                ('icon', models.CharField(choices=[('fa-brands fa-python', 'Python'), ('fa-brands fa-html5', 'HTML'), ('fa-brands fa-css3-alt', 'CSS'), ('fa-brands fa-js', 'JavaScript'), ('fa-solid fa-wind', 'Tailwind CSS'), ('fa-solid fa-leaf', 'Django'), ('fa-solid fa-database', 'MySQL'), ('fa-brands fa-react', 'React'), ('fa-solid fa-code', 'Other')], default='fa-solid fa-code', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, to='core.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
