# Generated by Django 5.2 on 2025-05-06 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='shadow',
            field=models.CharField(choices=[('green', 'hover:shadow-[0_0_20px_#00FF00]'), ('blue', 'hover:shadow-[0_0_20px_#3b82f6]'), ('red', 'hover:shadow-[0_0_20px_#ef4444]')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
