# Generated by Django 5.2 on 2025-05-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_options_project_color_project_shadow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
