# Generated by Django 5.2 on 2025-05-06 03:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JavaScript'), ('Python', 'Python'), ('Django', 'Django'), ('React', 'React')], max_length=31),
        ),
    ]
