# Generated by Django 5.2 on 2025-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=80, help_text='Skill level as a percentage'),
        ),
    ]
